(in-package :chimacho)

;; 単なるショートカット
(defmacro bq (form) `(back-quote ,form))

(progn
(assert (equal 1 (bq 1)))
(assert (equal '(a) (bq (a))))
(assert (equal '(a b) (bq (a b))))
(assert (equal '(1 b) (let ((a 1)) (bq ((comma a) b)))))
(assert (equal '(a 2) (let ((b 2)) (bq (a (comma b))))))
(assert (equal '(1 (2 3)) (let ((a '(2 3))) (bq (1 (comma a))))))
(assert (equal '(1 (2 3) 4) (let ((a '(2 3))) (bq (1 (comma a) 4)))))
(assert (equal '(1 2 3) (let ((a '(2 3))) (bq (1 (comma-at a))))))
(assert (equal '(1 2 3 4) (let ((a '(2 3))) (bq (1 (comma-at a) 4)))))
(assert (equal '((1)) (bq ((1)))))
(assert (equal '((1)) (let ((a 1)) (bq (((comma a)))))))
(assert (equal '(let ((a 1) (b 2)))
               (bq (let (comma ($mapcar #'list '(a b) '(1 2)))))))
(assert (equal ''a (let ((x '(a))) (bq  '(comma (car x))))))
(assert (equal '(let () 'a)
               (let ((x '(a)))
                 (bq (let ()
                       '(back-quote (comma (comma (car x)))))))))
)
